# fly.toml app configuration file generated for yesim-backend on 2025-07-07T00:55:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yesim-backend'
primary_region = 'dfw'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'node prisma/seed.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
